### ISSUE TITLE
Getting Permission Denied Error when Installing with NPM

### ISSUE THREAD

**Issue by flrrrhoffpauir** [contentful/contentful.js#211] opened 2017-11-30 21:31 UTC
* **Node Version**: v8.2.0
* **Npm Version**: 5.2.0
* **Platform**: Darwin Junies-MacBook-Pro-2.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
* **Package Version**:

When I run `sudo npm install contentful` I get the following error:
```
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git clone --depth=1 -q -b fix/https-via-http-proxy git://github.com/contentful/axios.git /Users/juniethreatt/.npm/_cacache/tmp/git-clone-e4d5168e
npm ERR! /Users/juniethreatt/.npm/_cacache/tmp/git-clone-e4d5168e/.git: Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juniethreatt/.npm/_logs/2017-11-30T21_24_50_080Z-debug.log
```

I previously have `"contentful": "^4.3.0",` installed, but while trying to update other node packages, I got that error and now it seems it's not installed at all anymore

**Comment by axe312ger** [comment] 2017-12-07 13:19
Sounds like a problem related to your machine for me. Also, you should never use `sudo` in combination with npm. I'd guess your file permissions are broken in your npm folder, you may try:

* delete your npm cache
* reset the permissions of your `/Users/juniethreatt/.npm/` recoursively to your user. 

See here:
* https://docs.npmjs.com/getting-started/fixing-npm-permissions
* https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache

**Comment by Khaledgarbaya** [comment] 2018-02-26 12:31
I am closing this issue for as it seems like the issue is fixed

**Closed by Khaledgarbaya** 2018-02-26 12:31 UTC
Labels: question

**Comment by sdelvalle57** [comment] 2018-10-04 03:12
I did 
`sudo npm cache clean -f`

For me that did the trick

**Comment by KoKim2020** [comment] 2020-04-18 07:21
thanks you so mush brother axe312ger

**Comment by xeptore** [comment] 2021-02-14 05:42
I found this link in the office doc helpful:
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
