### ISSUE TITLE
Issue with linked fields and the preview API

### ISSUE THREAD

**Issue by brendanmckenzie** [contentful/contentful.js#104] opened 2016-12-22 01:19 UTC
* **Node Version**: v6.7.0
* **Npm Version**: 3.10.7
* **Platform**: Darwin Brendans-MacBook-Pro.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
* **Package Version**: contentful@3.8.0

I have encountered an issue with the Preview API using the contentful.js library.  When running the `sync` method, automapping of linked properties appears to not be working as expected.  This is, however, working as expected on Production API.  See the below two examples.

n.b. `featuredContent` is a "References, many" type of field

This example is run against the Production API

```
> const contentful = Contentful(axios, { space: '...', accessToken: '...', host: 'cdn.contentful.com' })
> contentful.sync({ initial: true }).then(res => { global.sync = res; console.log('done') })
> const x = sync.entries.filter(ent => ent.sys.id === '{{wellKnownContentId}}')[0]
> x.fields.featuredContent['en-AU'][0]
{ sys:
   { ... },
  fields:
   { ... } }
```

This example is run against the Preview API

```
> const contentful = Contentful(axios, { space: '...', accessToken: '...', host: 'preview.contentful.com' })
> contentful.sync({ initial: true }).then(res => { global.sync = res; console.log('done') })
> const x = sync.entries.filter(ent => ent.sys.id === '{{wellKnownContentId}}')[0]
> x.fields.featuredContent['en-AU'][0]
{ sys: { ... } }
```

Note the lacking `fields` property on the returned object.

All pieces of content related to these examples are published and have no unpublished modifications.

**Comment by Khaledgarbaya** [comment] 2017-01-02 09:35
@brendanmckenzie ,
Sorry for that, there is a little bit of inconsistency between the two hosts. I am planning to make a workaround to fix that SDK level.

**Comment by Khaledgarbaya** [comment] 2017-11-06 12:58
The problem is fixed on API level

**Closed by Khaledgarbaya** 2017-11-06 12:58 UTC
Labels: bug
