### ISSUE TITLE
Preview API deep linked items

### ISSUE THREAD

**Issue by taylor-verys** [contentful/contentful.js#178] opened 2017-07-27 15:54 UTC
* **Node Version**: v7.2.0
* **Npm Version**: 3.10.9
* **Platform**: Darwin *.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
* **Package Version**: contentful@3.8.1

This issue is similar to #104 – however in this case I'm not attempting to use the Sync API. 

```
    client.getEntries({    
      content_type: 'content_type',
      include: 4,
      locale: '*'
    })
```

A good response would include all my deep linked data at `data.foo.fields.xxx`. However occasionally I'll get a response that is missing the `fields` object. I'm aware these issues have been known to occur using the Sync API, this is just a normal request.

This does not occur with every request, I would say I was getting a repro rate of about 4/10.

**Comment by axe312ger** [comment] 2017-07-28 08:13
Hey Taylor,

thank you for your bug report. I need to ask a few questions:

Are you getting this on 4 out of 10 on the very same request or do you have 10 different requests with only 4 containing the fields data?

I wonder if it is a bug on API or SDK level. Does your response contain id's of the linked entries or are they missing the data completely?

If you can, an example response would be pretty helpful. Feel free to remove any critical content from it :)

All the best, 
Benedikt

**Comment by DWethmar** [comment] 2017-08-17 16:05
I have the same issue when using locale: '*'

When i use for example locale: "en-US" it works.

**Comment by Khaledgarbaya** [comment] 2017-08-18 11:11
which version of the SDK are you using ?

**Comment by axe312ger** [comment] 2017-08-21 08:37
@DWethmar I have trouble replicating the issue. Are you able to post a response where you mark the position where the fields are missing? 

Is it for Content within the `includes` array? Or the "regular" Content in the response? Does it also happen at only 4/10 times like the original post or are you able to replicate it every time?

Thank you,
Benedikt

**Comment by taylor-verys** [comment] 2017-08-23 17:38
@axe312ger I'll provide you with an example response when I get a chance however I'll answer your other questions.

I meant out of 10 requests, 4 of them will come back with missing data. From what I saw, the response did contain the `id` of the linked data in the `sys` object, however no fields were returned. This is the data contained in the "regular" content in the response. Worth noting I'm also using the `*` to return all locales. 

I'm seeing this happen when rapidly making requests. In my case, a request is made each time a link is clicked. If the links are clicked rapidly, eventually one of the responses will have missing data. Again, this is **only** in the Preview API.

**Comment by axe312ger** [comment] 2017-08-24 08:14
Hey Taylor,

I talked to one of our API engineers and we would ask you if you may open a ticket in our support ticketing system. For proper debugging, he might need to impersonate you which we can not do via GitHub issues.

You can do it here: https://www.contentful.com/support/

He will then grab the ticket and investigate after you provided more detailed information (What you do and when it happens) and then fixing the bug :)

Good luck,
Benedikt

**Comment by sgronblo** [comment] 2017-09-06 05:19
@taylor-verys @DWethmar Could you verify if you have the same problem as me? I noticed that when link resolution is failing the entries have both a `sys.locale` value and the each of the fields also have locale keys (because of the `'*'` usage). Contentful.js seems to be checking if an entry has `sys.local` set to determine how to create the getters which I think fails in the case where sys.locale is defined.

**Comment by axe312ger** [comment] 2017-09-20 15:54
Closing as duplicate, please check my last update at https://github.com/contentful/contentful.js/issues/186

**Closed by axe312ger** 2017-09-20 15:54 UTC
Labels: awaiting feedback

**Comment by axe312ger** [comment] 2017-10-16 09:48
In case you are only following this ticket: The problem is fixed on API level, more details here -> https://github.com/contentful/contentful.js/issues/186#issuecomment-336833073
