### ISSUE TITLE
adapter is not a function when used in NextJS SSR

### ISSUE THREAD

**Issue by tgoyer** [contentful/contentful.js#1726] opened 2023-03-01 19:28 UTC
## Expected Behavior
I can use the library to fetch data from my CMS repo in a NextJS server-side page call (or any Node.js script).

## Actual Behavior
Using the Javascript client in a Server-side page, I get a `adapter is not a function` error.

## Possible Solution
Switch from using `Axios` to `fetch` for data fetching as is ubiquitous in both browsers and Node servers.

## Steps to Reproduce
1.  Create a bare-bones NextJS app.
2.  NPM install the contentful.js library
3.  Make a server-side data fetch.

## Context
This issue has been documented in the following ticket: https://github.com/vercel/next.js/issues/30932
The problem is that axios < v1.0 delegates into `XMLHttpRequest` which does not exist in a server environment.  I recommend you to use native fetch or upgrade to the most current version (> v1) of `Axios`.

## Environment
All environments

**Comment by Vinz93** [comment] 2023-03-28 14:01
Hey @tgoyer  👋

I tried to reproduce the bug you reported, and it works when you run contentful in `getServerSideProps` or in any node environment.

I was able to reproduce the bug by  changing the runtime to "edge", it seems that bumping Axios does not resolve the issue, but I found a work around and is providing a custom adapter that uses fetch instead.

I have this example where I use `axios-fetch-adapter` and it solved the apter issue in the edge runtime.

```
import fetchAdapter from "@vespaiach/axios-fetch-adapter";
import * as contentful from 'contentful';
import { NextRequest, NextResponse } from "next/server";

export const config = {
  runtime: "edge",
};

const getMyEntry = async () => {
  const client = contentful.createClient({
    space: 'space-id',
    accessToken: 'token',
    adapter: fetchAdapter
  })

  const entry = await client.getEntry("3Bngp0I3WWZ73JxT71euVe"); 
  return entry;
};

export default async function handler(req: any, res: any) {
  const entry = await getMyEntry();

  return NextResponse.json({ entry });
}
```
Please let me know if this approach works for you
Cheers

**Comment by marcolink** [comment] 2023-04-20 13:28
Closing this for now due to new response

**Closed by marcolink** 2023-04-20 13:28 UTC
