### ISSUE TITLE
Contentful.js doesn't work with Nuxt3

### ISSUE THREAD

**Issue by thiagorossener** [contentful/contentful.js#1233] opened 2022-04-26 20:22 UTC
## Expected Behavior

Contentful.js SDK works with Nuxt3 when building for production.

## Actual Behavior

When creating a plugin to use Contentful:
```
import * as contentful from "contentful";
```

It works fine locally when running `npm run dev`.

However, when building for production, this happens:
```
[nuxt] [request error] contentful.createClient is not a function
```

## Steps to Reproduce

1. Create an entry with a "title" field in Contentful.
2. Create a project using Nuxt3:
```npx nuxi init nuxt-app```
```cd nuxt-app```
3. Install Contentful.js
```npm install contentful -D```

4. Create the file `plugins/contentful.js` and add:
```js
import * as contentful from "contentful";

export default defineNuxtPlugin((nuxtApp) => {
  const client = contentful.createClient({
    space: "YOUR_SPACE_ID",
    accessToken: "YOUR_ACCESS_TOKEN",
  });

  nuxtApp.provide("contentfulClient", client);
});
```
5. Then, in `app.vue`:

```vue
<template>
  <div>
    {{ entry.fields.title }}
  </div>
</template>

<script setup>
  const { $contentfulClient } = useNuxtApp();
  const entry = await $contentfulClient.getEntry("YOUR_ENTRY_ID");
</script>
```

6. Run `npm run dev` and see that the title appears as expected.
7. Run `npm run build`, then `npm run preview`. An error 500 occurs, in the log you see:
`[nuxt] [request error] contentful.createClient is not a function`

## Context

I'm trying to deploy my application on Netlify.

## Environment

-   **Language Version**: Node v16.14.0
-   **Package Manager Version**: NPM 8.3.1
-   **Browser Version**: Version 100.0.4896.127 (Official Build) (x86_64)
-   **Operating System**: macOS Monterey v12.2.1`Darwin *** 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64`
-   **Package Version**: `"contentful": "^9.1.25"` and `"nuxt": "3.0.0-rc.1"`
-   **Which API are you using?**: Trying to use Contentful JavaScript Content Delivery Library

**Comment by davidwarrington** [comment] 2022-05-02 21:02
I've run into the same issue in an Astro project. Interestingly in my case I only have this issue when building the site, not whilst Vite is running in watch mode.

I've played around with the stable and beta version of this package, along with named vs default imports and found this combination to work for me in both dev and production mode:

Install the beta version with
```
yarn add contentful@beta-v10
```

Then switch your usage like this
```diff
- import { createClient } from 'contentful';
+ import contentful from 'contentful';

- export const client = createClient({...});
+ export const client = contentful.createClient({...});
```

**Comment by denisedelbando** [comment] 2022-06-24 17:25
What is the difference between the two?
```
import { createClient as createClientOrig } from 'contentful'; 
import { createClient as createClientToo } from 'contentful-management';
```

**Comment by christiankozalla** [comment] 2022-07-08 07:00
@thiagorossener in your steps to reproduce, step 3, you are installing the contentful client as a dev-dependency (-D). However, it is used in production, so I recommend to install it as a regular dependency (npm install contentful). Also, it kind of makes sense, that you say it works on development, but not after building the app in production.

**Comment by codyslex1a** [comment] 2022-08-14 16:27
> contentful@beta-v10

Your solution is not working.

In short, this is a problem when using contenful.js with Vite.

**Comment by fmarcheski** [comment] 2022-08-16 05:37
I had this same issue. Worked in Dev, but not in Production.
The below code solved my problem. Basically, in Production you must use contentful.createClient. In Dev you can use createClient.

Hope this helps someone else.

`import { createClient } from "contentful";
import contentful from 'contentful'

export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig();

  const createClientFunc = process.env.NODE_ENV === 'development' ? createClient : contentful.createClient

  const client = createClientFunc({
    space: config.CTF_SPACE_ID,
    accessToken: config.CTF_CDA_ACCESS_TOKEN,
  });

  console.log("client: ", client);

  return {
    provide: {
      contentfulClient: client,
    },
  };
});
`

**Comment by fmarcheski** [comment] 2022-08-16 05:46
I had this same issue. Worked in Dev, but not in Production.
The below code solved my problem. Basically, in Production you must use **contentful.createClient**. In Dev you can use **createClient**.

Hope this helps someone else.

``````
import { createClient } from "contentful";
import contentful from 'contentful'

export default defineNuxtPlugin((nuxtApp) => {
  const config = useRuntimeConfig();

  const createClientFunc = process.env.NODE_ENV === 'development' ? createClient : contentful.createClient

  const client = createClientFunc({
    space: config.CTF_SPACE_ID,
    accessToken: config.CTF_CDA_ACCESS_TOKEN,
  });

  return {
    provide: {
      contentfulClient: client,
    },
  };
});
```````

**Comment by thiagorossener** [comment] 2022-08-16 14:00
Thanks @fmarcheski! I had to do the same thing, ended up forgetting to post it here. That solution works for me too.

**Comment by JackEdwardLyons** [comment] 2022-11-01 09:25
Any updates on a fix for this? I've tried the suggestions above, but no success.
Running on `"contentful": "^10.0.0-beta-v10.8"` and `"nuxt": "npm:nuxt3@latest"`.
Getting either this error `Named export 'createClient' not found.` or the error from the OP.

**Comment by marcolink** [comment] 2022-11-01 09:46
Hi @JackEdwardLyons,
Sorry to hear you're still running into this issue! Unfortunately, I have personally no experience with `nuxt`. 
I have tried to create a very basic example to understand what is going on- maybe you want to have a look? 

As far as I can see the import is working fine - the only error I see is expected (no space id and credentials provided, therefore also no entries returned)

https://codesandbox.io/s/condescending-nightingale-bkvx51

**Comment by JackEdwardLyons** [comment] 2022-11-01 10:22
Hi @marcolink thanks for the quick response. I appreciate it.
I had a look at your codesandbox link and it is using `"nuxt": "^2.15.0"`.

I forked it and bumped the version to the latest RC release, and now it's not loading correctly. Please take a look:

https://codesandbox.io/s/small-breeze-5fnx3x

**Comment by marcolink** [comment] 2022-11-01 11:08
@JackEdwardLyons 
Changed the export/import of the plugin to use defaults, but now I get a different error

https://codesandbox.io/s/great-dust-v0oqz8

```
 ERROR  Nitro is not initialized yet. You can call useNitro() only after ready hook.             
 ```
 
Not sure what it means?

**Comment by JackEdwardLyons** [comment] 2022-11-01 19:47
Hi @marcolink I checked your fork, and set the nuxt verion to the latest RC. Still getting the 502 error in codesandbox, but the nitro error is gone. I'll need to work on a proper replication for this issue.

But do you have any knowledge as to why it should work for the solution by @fmarcheski above?

**Comment by JackEdwardLyons** [comment] 2022-11-02 00:49
Hey @marcolink just want to say thanks for the help and that it's likely a Nuxt/Vite issue or something else on my side. I don't think you need to look into this any more.

**Comment by ruriarte-zaelot** [comment] 2023-01-23 20:39
> Hey @marcolink just want to say thanks for the help and that it's likely a Nuxt/Vite issue or something else on my side. I don't think you need to look into this any more.

Hey Jack have you found a way to solve this, I am really not getting it to work, I am getting the same error messages.

**Comment by marcolink** [comment] 2023-01-23 20:43
@ruriarte-zaelot what version of `contentful.js` are you using?

**Comment by ruriarte-zaelot** [comment] 2023-01-23 20:48
> @ruriarte-zaelot what version of `contentful.js` are you using?

Hey marco thanks for your quick response. I'm using version 9.2.17

**Comment by marcolink** [comment] 2023-01-23 20:58
Ok, that version introduces a fix for ESM builds. 
I'm completely unexperienced with VUE and NUXT, but does this work: 
https://codesandbox.io/p/sandbox/nuxt-with-contentful-m1bwfp

**Comment by ruriarte-zaelot** [comment] 2023-01-23 21:57
@marcolink The problem I'm facing is that the way you imported in the sandbox is working for me but only in local. Same problem @thiagorossener was having. When I deploy to dev/production it throws this error. 
```
Named export 'createClient' not found. The requested module 'contentful' is a CommonJS module, which may not support all module.exports as named exports.

CommonJS modules can always be imported via the default export, for example using:

import pkg from 'contentful';

const { createClient } = pkg;
```
What worked best for me so far was to use the procedure suggested by @fmarcheski . That is working but only for v10beta, not for v9.

**Comment by adi-kumar** [comment] 2023-02-15 06:56
I am also having this issue in my current application using `nuxt:3.0.0` and `contentful:9.2.17`. 
@ruriarte-zaelot To confirm, were you able to resolve the error you mentioned by switching to the v10beta release? What version of nuxt were you using?

**Comment by eriklindgren** [comment] 2023-03-06 15:41
You don't need to switch to the beta version of contentful to fix this. The beta version seems to have some issues (it didn't respect the `include` setting on my calls when I tried it for example). In the built server, the `createClient` function ends up on the `contentful.default` object instead of the `contentful` object. I'm sure there's an explanation, probably something to do with interoperability between CommonJS and ES Modules.

Anyway, I solved it like this:
```
import * as contentful from 'contentful'

const client = contentful.createClient
    ? contentful.createClient({...})
    : contentful.default.createClient({...})
```

I'm using nuxt 3.2.3 and contentful 9.3.3.

**Comment by andylemaire** [comment] 2023-03-14 20:44
@eriklindgren when using that solution, I keep getting an error in development: `util.inherits is not a function`

The strange thing is that I only get this when it's conditional. When doing `const client = contentful.createClient({...})` there's no problem at all.

I've used exactly the same versions as you, but I also tried the latest versions of both packages.

**Comment by SatoshiRoppongi** [comment] 2023-03-18 08:57
Cannot find contentful.default..

**Comment by eriklindgren** [comment] 2023-03-19 21:53
> Cannot find contentful.default..

The solution still works for me on nuxt 3.3.1 and contentful 9.3.5. I build the app with `nuxi build` and then run it with `node .output/server/index.mjs`. In the server/shell, the `contentful.default` object has the `createClient` function and in the client/browser the `createClient` function is on the `contentful` object itself.

If I run the app with `nuxi dev`, the `createClient` function is on the `contentful` object in both server and client 🤷

**Comment by rutgerbakker95** [comment] 2023-03-23 17:29
> Cannot find contentful.default..

I had to ignore this with `/* eslint-disable import/namespace */`. The solution from @eriklindgren is working for me.

- Operating System: `Darwin`
- Node Version:     `v18.14.1`
- Nuxt Version:     `3.3.1`
- Nitro Version:    `2.3.1`
- Builder:          `vite`
- User Config:      `target`, `ssr`, `experimental`, `runtimeConfig`, `build`, `tailwindcss`, `vite`, `css`, `image`, `modules`, `i18n`

**Comment by lisaschumann** [comment] 2023-04-21 12:19
For me, @fmarcheski solution worked like a charm! Thank you.

**Comment by peeyushsingla** [comment] 2023-08-29 10:27
I am importing with `import * as contentful from 'contentful';` and observed the structure of contentful object differs when running dev server vs build

dev server
```
{
  contentful: Object [Module] {
    createClient: [Getter],
    createGlobalOptions: [Getter]
  }
}
```

build
```
{
  contentful: [Module: null prototype] {
    contentful: undefined,
    default: Object [Module] {
      createClient: [Getter],
      createGlobalOptions: [Getter]
    }
  }
}
```

**Comment by danemauland** [comment] 2023-09-25 19:46
This is a known issue when using Vite for server side rendering a CommonJS module, but it sounds like they're looking into fixing it for Vite 5. [This issue thread](https://github.com/vitejs/vite/issues/2139) has more information. One more potential fix would be to import contentful this way:

`import contentful from 'contentful/dist/contentful.node.min.js';`

But then you'll also want to polyfill `global` in your index.html file:

```<script type="application/javascript">
  if (global === undefined) {
    var global = window;
  }
</script>```

**Comment by marcolink** [comment] 2023-10-11 11:45
closing this for now

**Closed by marcolink** 2023-10-11 11:45 UTC

**Comment by larsdouweschuitema** [comment] 2024-05-08 08:56
It seems they stated it as fixed on the `vite` issue. However, I am experiencing the exact same issue on the latest version of `contentful` using the following `nuxt` and `vite` versions:

```ts
"contentful": "^10.9.3",
"nuxt": "^3.11.2",
"vite": "5.2.11"
```

**Comment by Loque-** [comment] 2024-06-19 10:12
I just wanted to add that I am also experiencing this issue with Vite and Contentful and were able to resolve it with: https://github.com/cyco130/vite-plugin-cjs-interop
