### ISSUE TITLE
Circular references wheen include is >= 2

### ISSUE THREAD

**Issue by blackxored** [contentful/contentful.js#249] opened 2018-05-24 14:19 UTC
When setting a `getEntries` with an `include` of 2, I'm still getting circular references and being unable to `JSON.stringify` it.
In addition, `toPlainObject` does nothing, and `stringifySafe` just blocks forever.

**Comment by Khaledgarbaya** [comment] 2018-05-25 08:27
Hi @blackxored ,
Can you provide more details about your content model and how it is structured

**Comment by mike-rotate** [comment] 2018-06-21 18:21
I don't think this is the right place - but if this could be fed back upstream to Contentful itself that would be great... 

Please could someone introduce a warning within Contentful CMS when you have created a circular reference or pre-emptivley warn if you're about to create a circular reference - spent many hours on this issue then found this great tool which instantly highlighted the 2 way reference i had buried away https://contentful-graph.yaraslav.com/

**Comment by m-bodmer** [comment] 2018-07-12 23:48
I am having the same issue.

I tried to debug the content model I have, which exists 94 entries. These can be condensed to something like:

**Content Model Name:** Note
**Fields:**
- Note number (1-1000+)
- Related Note (References, many)

. If I have a set of notes such as:

**Note 1:**
- Note number: 1
- Related Notes: [2, 3]

**Note 2:**
- Note number: 2
- Related Notes: [1, 3]

**Note 3:**
- Note number: 3
- Related Notes: [2]

The related notes references results in a circular relationship. I tried to use `json-stringify-safe` to no avail. With the amount of circular relationships that exist in my 94 entries, the JSON I get is a total of 150MB, where is should be closer a bit less than 1MB.

Example output of `json-stringify-safe`:
```
~.contentful.note.6.fields.relatedNotes.1.fields.relatedNotes.0.fields.relatedNotes.0.fields.relatedNotes.2.fields.relatedNotes.0.fields.relatedNotes.2.fields.relatedNotes.1.fields.relatedNotes.1]"
```

**Comment by axe312ger** [comment] 2018-07-13 11:13
We will discuss this next week and try to come up with solutions. 

If you use `include: 2`, you just ensure that the API response does [only include entries 2 level deep in the relation/link chain](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/links/retrieval-of-linked-items). It does not affect the JS SDKs link resolution itself.

`json-stringify-safe` wasn't touched for a while, I wonder if these two newer projects can handle the circular dependencies better, you might give them a try:
* https://github.com/debitoor/safe-json-stringify
* https://github.com/davidmarkclements/fast-safe-stringify

Can you please provide me with more information about your use case in your application and why you need to stringify it?
Also, we'd need the exact version of the `contentful` package you are using since we did changes to link resolution in the not so far past.

Thanks a lot,
Benedikt

**Comment by joemarkevicius** [comment] 2018-07-13 13:52
@axe312ger I use contentful 5.1.3. My use case is this: I have 'article' as content type. It uses 'reference' field, so that content editor is able to add related articles to it. Response from the CMS returns the whole article within 'reference', meaning that this related article has its own 'reference' that has its own articles, etc. One idea that comes to mind is shallow reference. For example: 'article' could have 'shallow reference' where related articles would be reference by their IDs and nothing else. So, if I wanted more information about those articles, I would have to fetch them individually. Does this help?

**Comment by axe312ger** [comment] 2018-07-13 15:23
You can do this:
* set `resolveLinks: false` in the client to get these `shallow reference` you want
* You can find all articles in the `response.includes.Entries` array, no need to fetch them on your own. 
`include: X` defines how deep our system will look for linked entries and all of them will be in there for manual link/reference resolution.

But I still wonder what your actual problem is, yes, stringifying might be nasty due to your data model, but your application should not travel all dependencies on its own.

I assume that you just want to show one article per page, displaying links with title & image below as `related articles`. To do this, you may just grab the referenced articles from the entry, loop through them and render the output. You will never execute references deeper.

Don't get me wrong, I just want to see if this is an issue with solving a problem in your application or if it is just you want to see the data for debugging purposes. This is because debugging is the only moment where I ended up once in this situation with a particular data model.

If you are able to, a dump of your content structure would help a lot:

```
contentful space export --skip-content
```

Best,
Benedikt

**Comment by joemarkevicius** [comment] 2018-07-13 16:52
@axe312ger thanks for that. I assume you're referencing `resolveLinks` mentioned here: https://www.contentful.com/developers/docs/javascript/tutorials/using-js-cda-sdk/ and _Links_ docs here: https://www.contentful.com/developers/docs/concepts/links/.

The problem is as you describe: I added 'related articles' (reference field), just so that I could add related article links, but that's when I ran into the circular references issue.

Here is the dump of my content structure: https://pastebin.com/YqqwGWaU

**Comment by m-bodmer** [comment] 2018-07-13 23:20
The `include` parameter does not help too much in solving the issue I am having. It still results in too large of a data set (60MB JSON file down from 150MB) when I have 95 entries of a certain content model.

I stringify the JSON coming from Contentful because I write the JSON to a file. 

I am using Contentful `^6.1.1`

**Comment by axe312ger** [comment] 2018-07-16 08:08
I am referencing `resolveLinks` from the README of this library (https://github.com/contentful/contentful.js#configuration)

Sorry, I still struggle to see how this is an issue of the SDK, as it is the data structure which is not able to be stored as JSON (if it is in a resolved state/format).

Additionally, I wonder how this can be an issue in creating an app which displays the data, even with circular references. (As long you don't write loops which automatically travel deeper in the link chain 🤷‍♂️ )

I stick to my already proposed solution: Disable link resolving to keep the links as is (id's instead of links to real objects) and everything will work fine to store that data into JSON.

If you need to resolve the links later on for your application logic, you may use https://github.com/contentful/contentful-resolve-response as this is the same plugin as the SDK uses.


Best,
Benedikt

**Comment by phoebeschmidt** [comment] 2018-09-27 16:13
Closing due to inactivity. Feel free to open another issue if something comes up.

**Closed by phoebeschmidt** 2018-09-27 16:13 UTC
Labels: awaiting feedback

**Comment by Mk-Etlinger** [comment] 2019-05-08 19:46
There's definitely a bug happening somewhere. Can we re-open this?

I'm currently using the Node Client("contentful": "^7.1.0", node -v: v10.12.0) and getting the following error:

TypeError: Converting circular structure to JSON

I have a Asset Wrapper content-type which has a field called exclusiveCountries which refs Countries.
So assetWrappers(CT) -> exclusiveCountries(field) -> Countries(CT, this will eventually reference assetWrappers)

My query looks like this:

const entries = await client.getEntries({
      'sys.id': countryId,
      include: 4,
    });

I need exactly 4 levels of links resolved and nothing more. However, on the 4th level of content the links are still being resolved all the way down the hierarchy.

Expected behavior:

include parameter actually limits the links resolved to 4, even on a linked, references many content-type. I'm assuming that it's also including 4 levels deep on that, which is throwing this error.

Happy to provide more info but trying to get the ball rolling again.

**Comment by cachrisman** [comment] 2019-06-07 09:39
@Mk-Etlinger Can you please provide more information about your use case in your application and why you need to stringify it? 

The `include` parameter is telling the API how many levels deep to go when looking for possible referenced entries to include in the response. What you are seeing when you say `However, on the 4th level of content the links are still being resolved all the way down the hierarchy.` is what the SDK does with the API response. The API has only included entries and assets which are referenced up to 4 levels deep, but because you have a circular reference where level 1 is referring to level 2 which is referring to level 1, the SDK, by default, will traverse the tree forever. Most likely you should use `resolveLinks: false` when creating the client so the SDK won't do anything to the raw API response. Like so:

```
const client = contentful.createClient({space: '<space_id>', accessToken: '<access_token>', resolveLinks: false})
const entries = await client.getEntries({'sys.id': countryId, include: 4})
```

Hope this helps!

**Comment by Mk-Etlinger** [comment] 2019-06-07 13:12
@cachrisman Hey thanks for your reply! I'm sending my response as JSON to the client to consume and therefore it's stringify'd.

> because you have a circular reference where level 1 is referring to level 2 which is referring to level 1, the SDK, by default, will traverse the tree forever. 

I actually have a circular reference on the 5th level deep. This is why I only want to include 4 levels deep and not resolve past that. So I would want the links to resolve down to the 4th level, the 5th being a of `{ type: 'link'}`

The hierarchy is like this:

Countries -> Homepage -> Categories -> Sub Categories -> Asset Wrappers(this has the exclusiveCountry field which refs Countries)

This is starting to make sense though, and I see your point(in this case I actually might need to include 5 levels, but let's keep it 4 for consistency sake). This is probably a feature rather than a bug. Let me see if I'm understanding correctly.

```javascript
const client = contentful.createClient({
    space: '<space_id>', 
    accessToken: '<access_token>', 
    resolveLinks: false
})
```

*Expected Behavior:*

Resolve all of the links up until the 4th level which is specified by the `include` parameter but do not resolve past that. So the 5th is a `{ type: 'link'}`which avoids the circular ref.

*Current Behavior:*

If `resolveLInks` is on, all links will be resolved that are included in the response, even if that includes circular JSON. `Include` doesn't have any effect on which links are resolved.

Do I have that right? How feasible would this be? 

From my perspective, if you won't want to `include` past a certain level, why would you want to `resolveLinks` past the 4th level?

Let me know if the above makes sense or if you need any more info.

Thanks!

**Comment by AlexandraKlein** [comment] 2020-10-23 04:32
+1 for reopening this.

I have Posts with Related Posts so when I fetch data, I get an infinitely deep object of Posts with Related Posts, with Related Posts, etc.

My code:

```javascript
export async function getPosts(slug, content_type, preview) {
  const entries = await contentfulClient(preview).getEntries({
    content_type: 'post',
    'fields.slug[in]': slug,
    include: 3
  });

  return entries;
}
```
Returns the following: 

```javascript
 items: {
    0: {
      fields: {
        title: 'article 1',
        relatedPosts: {
          0: {
            fields: {
              title: 'article 2',
              relatedPosts: {
                0: {
                  fields: {
                    title: 'article 3',
                    relatedPosts: {
                      0: {
                        fields: {
                          title: 'article 4',
                          relatedPosts: [....goes on forever....]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
```

**Comment by alvesvaren** [comment] 2023-07-19 16:45
This is still an issue with the latest version (10.3.5)...

**Comment by Sly36** [comment] 2025-01-27 16:49
Hello, any news on this issue ? 

I try to update contenful Javascript sdk from v9 to v11 (but I think the breaking changes comes from v10). With the v9 sdk, I was using the stringifySafe method to remove circular references.

```typescript
export const removeCircularReferences = (entries: EntryCollection<unknown>) => {
    return JSON.parse(entries.stringifySafe());
};
```

But now (from v10), I have this error `TS2339: Property stringifySafe does not exist on type EntryCollection`, and nothing in the documentation or migration guide about this subject. More than one year that I try to update from v9...
