### ISSUE TITLE
Add an option to avoid circular references in the object returned by `getEntries()`

### ISSUE THREAD

**Issue by jtomaszewski** [contentful/contentful.js#377] opened 2020-03-10 15:25 UTC
Currently I'm loading page's data (from Contentful) in a next.js [`getStaticProps` function](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation). After that,  I'm returning that data as a prop to my react page component.

However, `getStaticProps` function must not return JSON with circular references. If you do that, you end up with _"circular references cannot be expressed in JSON"_ error.

To go around it I had to call `.stringifySafe()` on the entries and then parse that stringified string, so I could end up with the same JSON object, but without the circular references in it:

```tsx
function removeEntryCollectionCircularReferences<T>(
  entries: EntryCollection<T>
): EntryCollection<T> {
  return JSON.parse(entries.stringifySafe()) as typeof entries;
}

export const getStaticProps: GetStaticProps = async context => {
  const pages = await contentfulClient.getEntries<IPageFields>({
    content_type: 'page',
    'fields.urlSlug': context.params.id
  });
  const page = removeEntryCollectionCircularReferences(pages).items[0];

  return { props: { page } };
};
```

However it is not ideal, as I'm stringifying and then parsing that whole JSON needlessly, also it requires me to have that util function. (I suspect more people will end up with similar problem soon.)

Ideally, maybe we could tell the Contentful Client not to fully serialize the linked entry, if it has been already included in the tree above it? It could be configured with a `resolveCircularReferences: boolean` option passed to the client or `getEntries()` method.

What do you think?

## Environment

- contentful.js 7.14.0
- next 9.3.0

**Comment by paulobmarcos** [comment] 2020-03-20 21:58
Same problem here. It's a strange behavior, or so it seems.

Imagine that we have the following:

**A** _---references--->_ **B** _---references--->_ **A** 

**Current Behavior:**

Even if you use the `include` parameter to limit the depth of resolved links, it will still return the last entry A fully resolved instead of a link.

**Expected Behavior:**

It would respect the `include` parameter and return the last A entry as a link.

**Note**

I have seen multiple issues open about this problem, even closed ones from a few years ago. Is there any expectation to tackle this problem?

_Originally posted by @paulobmarcos in https://github.com/contentful/contentful.js/issues/297#issuecomment-601924392_

**Comment by paulobmarcos** [comment] 2020-03-20 22:38
After checking who was responsible for transforming the result, I found it to be : [contentful-resolve-response](https://github.com/contentful/contentful-resolve-response).

Maybe that package should accept an option to go deep until a certain level.

In most cases, that deep level is the `include` parameter value.

**Comment by bryandowning** [comment] 2020-05-15 00:58
I just ran into this problem as well. In case anyone else lands here who also happens to be using [normalizr](https://www.npmjs.com/package/normalizr), the fix for this is SUPER simple — just update normalizr to at least 3.4.0 (3.5.0 would be better as performance improvements were introduced there).

normalizr supports normalizing circular references without you needing to do anything outside of defining your schemas and normalizing the contentful responses.

**Comment by patrickedqvist** [comment] 2020-08-11 18:12
I've tried @bryandowning approach using NextJS but without a redux implementation, it grows quite complex. You need some sort of global state management to access the output from normalize.

I have the following content structure:

**Page: Page A** ---references---> **Sections** ---references---> **Call To Action** ---references---> **Page: Page B**

Page B contains a field `parentPage` which is a reference to Page A. Overall my experience with Contentful has been great but creating hierarchical content with references is a pain and not something I have been able to find a good solution too when creating websites.

I will probably look into a solution that resolves **Call To Action** references to Pages so that it does not include the **Sections** reference field which is causing the circular reference.

**Comment by bryandowning** [comment] 2020-08-11 19:23
@patrickedqvist You really shouldn't need to resolve/flatten those Call To Action references, and doing it is a slippery slope. As long as you have a schema defined for Page, Sections, and Call To Action, AND you have all the fields pointing to the proper schemas — you should be good to go. However, setting all that up is a bit tricky. Here's some (incomplete) sample code that may help — I don't think it maps exactly to your setup, but it's close  and it communicates the idea:


```js
import { lensPath, view } from 'ramda'
import { schema } from 'normalizr'

// All of your section schemas get defined here
export const callToActionSchema = new schema.Entity('ctas')

// Create an object of all available section schemas
export const sectionSchemas = {
  callToAction: callToActionSchema,
}

// This is used to tell normalizr where to find the content type (using some helpers from ramda)
// The value in sys.contentType.sys.id needs to match an object key in sectionSchemas
export const lensEntityType = lensPath(['sys', 'contentType', 'sys', 'id'])
export function getEntityType(entity) {
  return view(lensEntityType, entity)
}

// Use schema.Union to allow many different schemas to be used for a "section"
export const sectionSchema = new schema.Union(sectionSchemas, getEntityType)

// Make your pages reference sections
export const pageSchema = new schema.Entity('pages', {
  sections: [sectionSchema],
})

// This is the tricky bit - use the define method to add fields to schemas after
// they have been declared. This is key to avoid circular reference issues with
// your code imports.
pageSchema.define({ parentPage: pageSchema })
callToActionSchema.define({ page: pageSchema })
```

**Comment by patrickedqvist** [comment] 2020-08-12 09:11
@bryandowning Thank you for your answer and valuable code example. I did try with something close to what you have shown. The problem is however with storing the results from the normalization in a way so it is easily accessible from a nested component. Now I can be wrong but from what I remember of using [next-redux-wrapper](https://github.com/kirill-konshin/next-redux-wrapper) is that you couldn't use it and also have static generation. Maybe that has changed.

Here is an example of what I believe I would need for accessing the results from a possibly nested component.

```.tsx
// CallToAction.tsx

interface Props {
  reference: string // The id we have from the normalizr result
  label: string
}

const LinkToPage = ({ reference, label )} => {
 
  const pages = useSelector(state => state.pages)
  const page = useSelector(state => state.pages[reference]);
  
  // Check if page has a parentPage and if that page also has a parent page and so on. 
  // Returns an array of strings. e.g ['page-a', 'page-b']
  const parentPages = resolveParentPageHierarchy(page, pages)

  const finalSlug = parentPages.length > 0 ? parentPages.join('/') + '/' + page.slug : page.slug

  return (
   <a href={finalSlug}>
      {label}
    </a>
  )
}
```
```.jsx
// Example - In a section
<div>
  <LinkToPage reference={section.callToAction} label={'Read More'} />
</div>

```

**Comment by bryandowning** [comment] 2020-08-12 17:46
@patrickedqvist I'm not aware of any reason static generation in Next wouldn't be possible when using some kind of global state management like Redux, but this may depend on your version of Next.

More info: https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation

But also check out this recent Syntax episode about state management — there are some really great alternatives to Redux: https://syntax.fm/show/272/react-state-round-up

**Comment by patrickedqvist** [comment] 2020-08-13 07:26
@bryandowning I've reread the documentation for next-redux-wrapper again, and it does no longer seem to force you to opt-out of static generation, however, if you use for example Redux-Saga then you must opt-out - "Keep in mind that this setup will opt you out of Automatic Static Optimization: [opt-out-auto-static-optimization](https://err.sh/next.js/opt-out-auto-static-optimization)". 

Redux saga has been my go-to package for handling side effects with Redux, and while it is not a requirement, it is very helpful. See [usage with redux saga](https://github.com/kirill-konshin/next-redux-wrapper#usage-with-redux-saga) for the documentation.

I agree with your side note.

**Comment by bryandowning** [comment] 2020-08-13 19:24
Interesting, thanks for pointing to that. However, worth noting that you're only opted out if you use getInitialProps in _app.js, which is not required for redux-saga:

https://github.com/kirill-konshin/next-redux-wrapper#usage-without-getinitialprops-inside-_app

**Comment by patrickedqvist** [comment] 2020-08-17 12:26
@bryandowning Oh, that was something I had missed. I will have to look into it and try it out.

**Comment by DanielOrtel** [comment] 2020-12-17 15:31
any word on this? We use immutableJS and store the data returned by `getEntries` in Redux, but immutable's `fromJS` breaks on circular dependencies completely. Sadly, there's no way atm to avoid immutable, so it'd be nice to have the option to make `getEntries` not circularly dependent.

**Comment by juanbiberretta** [comment] 2021-02-18 19:41
Same here, I'd for this to be at least looked at... We have to run out responses through a cycle remover on Gatsby otherwise it fails when trying to create pages.

**Comment by DerekLoop** [comment] 2021-09-27 23:24
Bump? 😊

**Comment by maapteh** [comment] 2022-04-13 18:03
https://raw.githubusercontent.com/contentful/contentful-resolve-response/master/README.md
the lib states: `Circular references are possible, still!!`

This is the first CMS where i will be very happy when the client ditches it. Who wants to use ten of their libs and still finding out it creates circulair dependencies. So on a FAQ pointing to another link on same page, you can't. As storage all this entries stuff is very powerfull, but as a consumer for its api im only interested in its flattened response which takes care of all this.

**Comment by maapteh** [comment] 2022-04-15 19:34
Yes, so my cullprit was everywhere where i used FreeText component. For the 'entry-hyperlink' im patching these to only include the title, link/slug and pass these back instead of a possible while data model of the page it links to. Hope this helps others!

**Comment by andreascful** [comment] 2022-04-21 09:16
Thank you @maapteh for providing your solution.
I'm closing this issue for now since it seems that there are solutions and/or workarounds for this issue given in the thread.
If anything pops up again we can definitely open it up again.

**Closed by andreascful** 2022-04-21 09:16 UTC
